Repository ansible-collections/community.zabbix, pull requests merged in 2020-06, with the labels that each got.

#69 dump_template from zabbix_template module should not exit module even…
  plugins/modules/zabbix_template.py
Labels: bug, module

#74 Renamed integration roles to prevent ansible-test confusing them with…
  tests/integration/targets/test_zabbix_group/meta/main.yml
  tests/integration/targets/test_zabbix_group/tasks/main.yml
  tests/integration/targets/test_zabbix_group_info/meta/main.yml
  tests/integration/targets/test_zabbix_group_info/tasks/main.yml
  tests/integration/targets/test_zabbix_host/meta/main.yml
  tests/integration/targets/test_zabbix_host/tasks/main.yml
  tests/integration/targets/test_zabbix_host/tasks/zabbix_host_doc.yml
  tests/integration/targets/test_zabbix_host/tasks/zabbix_host_setup.yml
  tests/integration/targets/test_zabbix_host/tasks/zabbix_host_teardown.yml
  tests/integration/targets/test_zabbix_host/tasks/zabbix_host_tests.yml
  tests/integration/targets/test_zabbix_hostmacro/meta/main.yml
  tests/integration/targets/test_zabbix_hostmacro/tasks/main.yml
  tests/integration/targets/test_zabbix_maintenance/meta/main.yml
  tests/integration/targets/test_zabbix_maintenance/tasks/main.yml
  tests/integration/targets/test_zabbix_proxy/meta/main.yml
  tests/integration/targets/test_zabbix_proxy/tasks/main.yml
  tests/integration/targets/test_zabbix_template/files/template1-changed.json
  tests/integration/targets/test_zabbix_template/files/template1.json
  tests/integration/targets/test_zabbix_template/files/template2.xml
  tests/integration/targets/test_zabbix_template/meta/main.yml
  tests/integration/targets/test_zabbix_template/tasks/main.yml
  tests/integration/targets/test_zabbix_user/meta/main.yml
  tests/integration/targets/test_zabbix_user/tasks/main.yml
  tests/integration/targets/test_zabbix_user_info/meta/main.yml
  tests/integration/targets/test_zabbix_user_info/tasks/main.yml
Labels: module

#85 updated CHANGELOG.md to reflect changes made in the collection
  CHANGELOG.md
Labels: documentation

#100 adjusted CI settings and naming to indicate that they do not include …
  .github/workflows/plugins.yml
  README.md
Labels: enhancement, module

#90 fixed zabbix_action to search for mediatype by its name in Zabbix 4.4+
  CHANGELOG.md
  plugins/modules/zabbix_action.py
Labels: Zabbix 5 support, bug, module

#97 WIP: Refactor Version dependencies in modules/plugins
  plugins/modules/zabbix_action.py
  plugins/modules/zabbix_group.py
  plugins/modules/zabbix_group_info.py
  plugins/modules/zabbix_host.py
  plugins/modules/zabbix_host_events_info.py
  plugins/modules/zabbix_host_info.py
  plugins/modules/zabbix_hostmacro.py
  plugins/modules/zabbix_maintenance.py
  plugins/modules/zabbix_map.py
  plugins/modules/zabbix_mediatype.py
  plugins/modules/zabbix_proxy.py
  plugins/modules/zabbix_screen.py
  plugins/modules/zabbix_service.py
  plugins/modules/zabbix_template.py
  plugins/modules/zabbix_template_info.py
  plugins/modules/zabbix_user.py
  plugins/modules/zabbix_user_info.py
  plugins/modules/zabbix_valuemap.py
Labels: enhancement, module

#105 Run CI against the correct branch
  .github/workflows/plugins.yml
  plugins/modules/zabbix_group_info.py
  plugins/modules/zabbix_host_info.py
  plugins/modules/zabbix_proxy.py
  plugins/modules/zabbix_template.py
  tests/integration/targets/test_zabbix_template/tasks/main.yml
  tests/sanity/ignore-2.11.txt
Labels: enhancement, module

#82 Added webhook and message template support to zabbix_mediatype
  CHANGELOG.md
  plugins/modules/zabbix_mediatype.py
  tests/integration/targets/test_zabbix_mediatype/tasks/main.yml
Labels: Zabbix 5 support, enhancement, module

#113 Integration tests for zabbix_action module with few adjusted fixes
  CHANGELOG.md
  plugins/modules/zabbix_action.py
  tests/integration/targets/test_zabbix_action/meta/main.yml
  tests/integration/targets/test_zabbix_action/tasks/main.yml
Labels: bug, enhancement, module

#117 fixed module references that should now include FQCN
  plugins/modules/zabbix_template.py
Labels: documentation, module
