Repository ansible-collections/community.zabbix, pull requests merged in 2021-12, with the labels that each got.

#562 Be able to specify a minor version for RH related deployments
  changelogs/fragments/414-specify-minor-version.yml
  docs/ZABBIX_AGENT_ROLE.md
  docs/ZABBIX_PROXY_ROLE.md
  docs/ZABBIX_SERVER_ROLE.md
  docs/ZABBIX_WEB_ROLE.md
  roles/zabbix_agent/defaults/main.yml
  roles/zabbix_agent/tasks/RedHat.yml
  roles/zabbix_javagateway/defaults/main.yml
  roles/zabbix_proxy/defaults/main.yml
  roles/zabbix_proxy/tasks/RedHat.yml
  roles/zabbix_server/defaults/main.yml
  roles/zabbix_server/tasks/RedHat.yml
  roles/zabbix_web/defaults/main.yml
  roles/zabbix_web/tasks/RedHat.yml
Labels: enhancement, role

#584 remove old versions in tests
  .github/workflows/plugins-integration.yml
  .github/workflows/repo-sanity.yml
Labels: enhancement

#597 Prepare for distutils.version being removed in Python 3.12
  changelogs/fragments/597-prepare-distutils.yml
  plugins/module_utils/helpers.py
  plugins/module_utils/version.py
  plugins/module_utils/wrappers.py
  plugins/modules/zabbix_action.py
  plugins/modules/zabbix_discovery_rule.py
  plugins/modules/zabbix_globalmacro.py
  plugins/modules/zabbix_host.py
  plugins/modules/zabbix_hostmacro.py
  plugins/modules/zabbix_map.py
  plugins/modules/zabbix_mediatype.py
  plugins/modules/zabbix_proxy.py
  plugins/modules/zabbix_template.py
  plugins/modules/zabbix_user.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.9.txt
  tox.ini
Labels: bug, enhancement
